---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-frontend-app
  template:
    metadata:
      labels:
        app: django-frontend-app
    
    spec:
      containers:
        - name: django-frontend-app
          image: registry.arqhabana.org:5005/ccpfv/dedalos-ccpfv-frontend:v0.1
          ports:
            - containerPort: 3005
          resources: {}  
          env:
            - name: DB_HOST
              value: postgresql-service
            - name: DB_NAME
              value: dedalos_ccpfv
            - name: DB_USER
              value: edr
            - name: DB_PASSWORD
              value: H@bana2019*
      imagePullSecrets:
        - name: dedalos-frontend-secret
