apiVersion: v1
kind: Service
metadata:
  name: django-frontend-service
spec:
  selector:
    app: django-frontend-app
  type: LoadBalancer
  
  ports:
  - name: http
    port: 80
    targetPort: 8009
